/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaoficios.gui;

import com.mycompany.sistemaoficios.gui.Herramientas;
import com.mycompany.sistemaoficios.gui.Catalogo;
import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.sistemaoficios.persistencia.HibernateUtil;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.hibernate.Session;

/**
 *
 * @author Keloc
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Image l1 = getImg("logo1").getImage();
    private Image l2 = getImg("logo2").getImage();
    public Main() {
        initComponents();
        logo1L.setIcon(resizeImage(l1, logo1L));
        logo2L.setIcon(resizeImage(l2, logo2L));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        optionMenuP = new javax.swing.JPanel();
        menubox = new javax.swing.JPanel();
        catalogoBtn = new javax.swing.JButton();
        nadaBtn = new javax.swing.JButton();
        supervisionBtn = new javax.swing.JButton();
        herramientasBtn = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logo1L = new javax.swing.JLabel();
        logo2L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setMinimumSize(new java.awt.Dimension(874, 461));
        bg.setPreferredSize(new java.awt.Dimension(874, 461));

        optionMenuP.setBackground(new java.awt.Color(204, 204, 204));

        menubox.setLayout(new javax.swing.BoxLayout(menubox, javax.swing.BoxLayout.PAGE_AXIS));

        catalogoBtn.setText("Catalogo");
        catalogoBtn.setBorder(null);
        catalogoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catalogoBtn.setMaximumSize(new java.awt.Dimension(175, 120));
        catalogoBtn.setMinimumSize(new java.awt.Dimension(175, 70));
        catalogoBtn.setPreferredSize(new java.awt.Dimension(175, 70));
        catalogoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoBtnActionPerformed(evt);
            }
        });
        menubox.add(catalogoBtn);

        nadaBtn.setText("Supervisión");
        nadaBtn.setBorder(null);
        nadaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nadaBtn.setMaximumSize(new java.awt.Dimension(175, 120));
        nadaBtn.setMinimumSize(new java.awt.Dimension(175, 70));
        nadaBtn.setPreferredSize(new java.awt.Dimension(175, 70));
        nadaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nadaBtnActionPerformed(evt);
            }
        });
        menubox.add(nadaBtn);

        supervisionBtn.setText("Supervisión");
        supervisionBtn.setBorder(null);
        supervisionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supervisionBtn.setMaximumSize(new java.awt.Dimension(175, 120));
        supervisionBtn.setMinimumSize(new java.awt.Dimension(175, 70));
        supervisionBtn.setPreferredSize(new java.awt.Dimension(175, 70));
        supervisionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supervisionBtnActionPerformed(evt);
            }
        });
        menubox.add(supervisionBtn);

        herramientasBtn.setText("Herramientas");
        herramientasBtn.setBorder(null);
        herramientasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        herramientasBtn.setMaximumSize(new java.awt.Dimension(175, 120));
        herramientasBtn.setMinimumSize(new java.awt.Dimension(175, 70));
        herramientasBtn.setPreferredSize(new java.awt.Dimension(175, 70));
        herramientasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramientasBtnActionPerformed(evt);
            }
        });
        menubox.add(herramientasBtn);

        javax.swing.GroupLayout optionMenuPLayout = new javax.swing.GroupLayout(optionMenuP);
        optionMenuP.setLayout(optionMenuPLayout);
        optionMenuPLayout.setHorizontalGroup(
            optionMenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menubox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        optionMenuPLayout.setVerticalGroup(
            optionMenuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionMenuPLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(menubox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        content.setMinimumSize(new java.awt.Dimension(899, 620));
        content.setPreferredSize(new java.awt.Dimension(899, 620));
        content.setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo1L, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo2L, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo1L, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo2L, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(optionMenuP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(optionMenuP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nadaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nadaBtnActionPerformed
        changeContent(new Supervision());
    }//GEN-LAST:event_nadaBtnActionPerformed

    private void catalogoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoBtnActionPerformed
        changeContent(new Catalogo());
    }//GEN-LAST:event_catalogoBtnActionPerformed

    private void supervisionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supervisionBtnActionPerformed
        changeContent(new Reportes());
    }//GEN-LAST:event_supervisionBtnActionPerformed

    private void herramientasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herramientasBtnActionPerformed
        changeContent(new Herramientas());
    }//GEN-LAST:event_herramientasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void changeContent(JPanel p){
        p.setSize(content.getWidth(), content.getHeight());
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    public static void main(String args[]) {
        FlatLightLaf.setup();
        Session session = HibernateUtil.getSessionFactory().openSession();
        try {
            session.beginTransaction();
            if (session.isConnected()){
                System.out.println("CONNECTION SUCCESS");
            }
        } catch(Exception e){
            if (session.getTransaction() != null) {
                session.getTransaction().rollback();
            }
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
           session.close();
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    private ImageIcon getImg(String n){
        ClassLoader classLoader = getClass().getClassLoader();
        java.net.URL iconURL = classLoader.getResource(n+".png");
        if (iconURL != null) {
            return new ImageIcon(iconURL);
        } else {
            System.err.println("No se pudo encontrar el icono");
            return new ImageIcon("src/main/resources/img/"+n+".png");
        }
    }
    
    private ImageIcon resizeImage(Image image, JLabel label){
        ImageIcon img = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
        return img;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton catalogoBtn;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JButton herramientasBtn;
    private javax.swing.JLabel logo1L;
    private javax.swing.JLabel logo2L;
    private javax.swing.JPanel menubox;
    private javax.swing.JButton nadaBtn;
    private javax.swing.JPanel optionMenuP;
    private javax.swing.JButton supervisionBtn;
    // End of variables declaration//GEN-END:variables
}
